apiVersion: v1
kind: Service

metadata:
  name: brainlens-prediction-api
  namespace: brainlens

spec:
  type: ClusterIP

  selector:
    app: brainlens-prediction-api

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000