import os
from pathlib import Path

import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

from .storage import load_prediction_events
from .window import (
    DEFAULT_WINDOW_HOURS,
    get_current_window,
)


# ============================================================
# CONFIGURATION
# ============================================================

WINDOW_HOURS = int(
    os.getenv(
        "MONITORING_WINDOW_HOURS",
        str(DEFAULT_WINDOW_HOURS),
    )
)

MIN_LABELED_SAMPLES = int(
    os.getenv(
        "MONITORING_MIN_LABELED_SAMPLES",
        "30",
    )
)

CLASS_NAMES = [
    "glioma",
    "meningioma",
    "no_tumor",
]


# ============================================================
# PATHS
# ============================================================

SERVICE_ROOT = Path(
    __file__
).resolve().parents[1]

REFERENCE_FILE = (
    SERVICE_ROOT
    / "data"
    / "reference"
    / "brainlens_reference_predictions.parquet"
)


# ============================================================
# LOAD REFERENCE DATA
# ============================================================

def load_reference_predictions() -> pd.DataFrame:
    """
    Load labeled reference predictions generated by the
    real BrainLens prediction API.
    """

    if not REFERENCE_FILE.exists():
        raise FileNotFoundError(
            "Reference prediction dataset not found: "
            f"{REFERENCE_FILE}"
        )

    dataframe = pd.read_parquet(
        REFERENCE_FILE
    )

    if dataframe.empty:
        raise ValueError(
            "Reference prediction dataset is empty."
        )

    return dataframe


# ============================================================
# PREPARE LABELED DATA
# ============================================================

def prepare_labeled_data(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Keep only predictions for which actual_class
    is available.
    """

    required_columns = [
        "predicted_class",
        "actual_class",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(
            "Missing performance columns: "
            f"{missing_columns}"
        )

    labeled = dataframe[
        dataframe["actual_class"].notna()
        & (
            dataframe["actual_class"]
            .astype(str)
            .str.strip()
            != ""
        )
    ].copy()

    return labeled


# ============================================================
# CALCULATE OVERALL PERFORMANCE
# ============================================================

def calculate_overall_performance(
    dataframe: pd.DataFrame,
) -> dict:
    """
    Calculate overall classification performance.
    """

    if dataframe.empty:
        raise ValueError(
            "No labeled predictions are available."
        )

    y_true = (
        dataframe["actual_class"]
        .astype(str)
    )

    y_pred = (
        dataframe["predicted_class"]
        .astype(str)
    )

    accuracy = accuracy_score(
        y_true,
        y_pred,
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            y_true,
            y_pred,
            labels=CLASS_NAMES,
            average="weighted",
            zero_division=0,
        )
    )

    return {
        "sample_count": int(
            len(dataframe)
        ),
        "accuracy": float(
            accuracy
        ),
        "precision_weighted": float(
            precision
        ),
        "recall_weighted": float(
            recall
        ),
        "f1_weighted": float(
            f1
        ),
    }


# ============================================================
# CALCULATE PER-CLASS PERFORMANCE
# ============================================================

def calculate_per_class_performance(
    dataframe: pd.DataFrame,
) -> dict:
    """
    Calculate precision, recall, F1, and support
    for each BrainLens class.
    """

    report = classification_report(
        dataframe["actual_class"].astype(str),
        dataframe["predicted_class"].astype(str),
        labels=CLASS_NAMES,
        target_names=CLASS_NAMES,
        output_dict=True,
        zero_division=0,
    )

    result = {}

    for class_name in CLASS_NAMES:

        class_metrics = report.get(
            class_name,
            {},
        )

        result[class_name] = {
            "precision": float(
                class_metrics.get(
                    "precision",
                    0.0,
                )
            ),
            "recall": float(
                class_metrics.get(
                    "recall",
                    0.0,
                )
            ),
            "f1": float(
                class_metrics.get(
                    "f1-score",
                    0.0,
                )
            ),
            "support": int(
                class_metrics.get(
                    "support",
                    0,
                )
            ),
        }

    return result


# ============================================================
# CONFUSION MATRIX
# ============================================================

def calculate_confusion_matrix(
    dataframe: pd.DataFrame,
) -> dict:
    """
    Calculate the confusion matrix using the fixed
    BrainLens class ordering.
    """

    matrix = confusion_matrix(
        dataframe["actual_class"].astype(str),
        dataframe["predicted_class"].astype(str),
        labels=CLASS_NAMES,
    )

    return {
        "labels": CLASS_NAMES,
        "matrix": matrix.tolist(),
    }


# ============================================================
# COMPLETE PERFORMANCE SUMMARY
# ============================================================

def calculate_performance(
    dataframe: pd.DataFrame,
) -> dict:
    """
    Calculate the complete BrainLens performance summary.
    """

    labeled = prepare_labeled_data(
        dataframe
    )

    if labeled.empty:
        raise ValueError(
            "No labeled predictions are available."
        )

    return {
        "overall": calculate_overall_performance(
            labeled
        ),
        "per_class": calculate_per_class_performance(
            labeled
        ),
        "confusion_matrix": calculate_confusion_matrix(
            labeled
        ),
    }


# ============================================================
# REFERENCE PERFORMANCE
# ============================================================

def calculate_reference_performance() -> dict:
    """
    Calculate the fixed baseline performance using
    the 709 labeled reference predictions.
    """

    dataframe = (
        load_reference_predictions()
    )

    return calculate_performance(
        dataframe
    )


# ============================================================
# PRODUCTION PERFORMANCE
# ============================================================

def calculate_production_performance(
    window_hours: int = WINDOW_HOURS,
) -> dict | None:
    """
    Calculate performance using labeled production
    predictions from the current monitoring window.

    Returns None when no labeled production predictions
    are available.
    """

    start_time, end_time = (
        get_current_window(
            window_hours
        )
    )

    dataframe = load_prediction_events(
        start_time=start_time,
        end_time=end_time,
    )

    if dataframe.empty:
        return None

    labeled = prepare_labeled_data(
        dataframe
    )

    if labeled.empty:
        return None

    return calculate_performance(
        labeled
    )

# ============================================================
# MONITORING FUNCTION
# ============================================================

def run_monitoring(start_time, end_time) -> dict:
    """
    Run model-performance monitoring for the current
    production monitoring window.

    Returns a structured monitoring result.
    """
    current_data = load_prediction_events(
        start_time=start_time,
        end_time=end_time,
    )

    current_count = len(
        current_data
    )

    # --------------------------------------------------------
    # No production events
    # --------------------------------------------------------

    if current_count == 0:
        return {
            "status": "INSUFFICIENT_DATA",
            "window_start": start_time.isoformat(),
            "window_end": end_time.isoformat(),
            "window_hours": (end_time - start_time).total_seconds() / 3600,
            "sample_count": 0,
            "labeled_sample_count": 0,
            "required_samples": MIN_LABELED_SAMPLES,
            "performance": None,
        }

    # --------------------------------------------------------
    # Keep only predictions with ground truth
    # --------------------------------------------------------

    labeled_data = prepare_labeled_data(
        current_data
    )

    labeled_count = len(
        labeled_data
    )

    # --------------------------------------------------------
    # Minimum labeled-sample gate
    # --------------------------------------------------------

    if labeled_count < MIN_LABELED_SAMPLES:
        return {
            "status": "INSUFFICIENT_DATA",
            "window_start": start_time.isoformat(),
            "window_end": end_time.isoformat(),
            "window_hours": WINDOW_HOURS,
            "sample_count": current_count,
            "labeled_sample_count": labeled_count,
            "required_samples": MIN_LABELED_SAMPLES,
            "performance": None,
        }

    # --------------------------------------------------------
    # Calculate performance
    # --------------------------------------------------------

    performance = calculate_performance(
        labeled_data
    )

    return {
        "status": "HEALTHY",
        "window_start": start_time.isoformat(),
        "window_end": end_time.isoformat(),
        "window_hours": WINDOW_HOURS,
        "sample_count": current_count,
        "labeled_sample_count": labeled_count,
        "required_samples": MIN_LABELED_SAMPLES,
        "performance": performance,
    }

# ============================================================
# MAIN
# ============================================================

def main() -> None:
    """
    Run model-performance monitoring from the command line.
    """

    print(
        "Running BrainLens performance monitoring..."
    )

    print(
        "\nReference performance:"
    )

    reference_performance = (
        calculate_reference_performance()
    )

    print(
        reference_performance
    )

    result = run_monitoring()

    print(
        "\nProduction performance result:"
    )

    print(
        result
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()