apiVersion: v1
kind: Service

metadata:
  name: brainlens-monitoring-service
  namespace: brainlens

spec:
  type: ClusterIP

  selector:
    app: brainlens-monitoring

  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001